import type { Block, CaseRow, ProofRow, Shelter, TaskRow, TaskTemplateRow } from '@/lib/types';

const now = Date.now();

function minutesAgo(minutes: number) {
  return new Date(now - minutes * 60_000).toISOString();
}

function minutesFromNow(minutes: number) {
  return new Date(now + minutes * 60_000).toISOString();
}

export type DemoCitizen = {
  id: string;
  device_id: string;
  block_id: string | null;
  created_at: string;
};

export const demoBlocks: Block[] = [
  { id: 'blk-indiranagar', name: 'Indiranagar', code: 'BLK-INDIR' },
  { id: 'blk-koramangala', name: 'Koramangala', code: 'BLK-KORA' },
  { id: 'blk-jayanagar', name: 'Jayanagar', code: 'BLK-JAYA' },
  { id: 'blk-whitefield', name: 'Whitefield', code: 'BLK-WHTF' },
];

export const demoShelters: Shelter[] = [
  { id: 'shelter-indiranagar', name: 'Indiranagar Shelter', block_id: 'blk-indiranagar', status: 'active' },
  { id: 'shelter-eastside', name: 'Eastside Rescue Collective', block_id: 'blk-koramangala', status: 'active' },
  { id: 'shelter-cubbon', name: 'Cubbon Care Network', block_id: 'blk-jayanagar', status: 'limited' },
  { id: 'shelter-whitefield', name: 'Whitefield Foster Circle', block_id: 'blk-whitefield', status: 'inactive' },
];

export const demoCitizens: DemoCitizen[] = [
  { id: 'citizen-001', device_id: 'demo-device-7f29-indiranagar', block_id: 'blk-indiranagar', created_at: minutesAgo(8_900) },
  { id: 'citizen-002', device_id: 'demo-device-23ac-koramangala', block_id: 'blk-koramangala', created_at: minutesAgo(7_100) },
  { id: 'citizen-003', device_id: 'demo-device-44ba-jayanagar', block_id: 'blk-jayanagar', created_at: minutesAgo(6_450) },
  { id: 'citizen-004', device_id: 'demo-device-98ef-whitefield', block_id: 'blk-whitefield', created_at: minutesAgo(4_220) },
  { id: 'citizen-005', device_id: 'demo-device-biscuit-feeder', block_id: 'blk-indiranagar', created_at: minutesAgo(2_400) },
  { id: 'citizen-006', device_id: 'demo-device-water-volunteer', block_id: 'blk-koramangala', created_at: minutesAgo(1_060) },
];

export const demoTaskTemplates: TaskTemplateRow[] = [
  { id: 'tpl-feed', type: 'feed', title: 'Feed', description: 'Offer safe food and submit a proof photo.', required_proof: 'photo', sla_minutes: 240 },
  { id: 'tpl-water', type: 'water_refill', title: 'Water Refill', description: 'Refill a water point and submit a proof photo.', required_proof: 'photo', sla_minutes: 240 },
  { id: 'tpl-rescue', type: 'rescue_assessment', title: 'Rescue Assessment', description: 'Assess the animal, capture proof, and escalate if needed.', required_proof: 'photo_location', sla_minutes: 60 },
  { id: 'tpl-medical', type: 'medical_check', title: 'Medical Check', description: 'Observe symptoms, capture proof, and recommend next step.', required_proof: 'photo_note', sla_minutes: 180 },
  { id: 'tpl-follow-up', type: 'follow_up', title: 'Follow Up', description: 'Revisit and confirm status update with proof.', required_proof: 'photo', sla_minutes: 360 },
  { id: 'tpl-transfer', type: 'intake_transfer', title: 'Intake / Transfer', description: 'Confirm safe transfer and handoff proof.', required_proof: 'note', sla_minutes: 120 },
  { id: 'tpl-proof-review', type: 'proof_review', title: 'Proof Review', description: 'Review proof quality and status.', required_proof: 'none', sla_minutes: 120 },
  { id: 'tpl-emergency', type: 'emergency_escalation', title: 'Emergency Escalation', description: 'Escalate to emergency response.', required_proof: 'none', sla_minutes: 15 },
];

export const demoCases: CaseRow[] = [
  {
    id: 'case-sy-7421',
    external_id: 'SY-7421',
    citizen_id: 'citizen-001',
    block_id: 'blk-indiranagar',
    shelter_id: null,
    category: 'rescue',
    severity: 'urgent',
    description: 'Dog trapped near market drain. Caller says traffic is heavy and animal cannot leave safely.',
    location_text: 'Indiranagar Market, 1st cross',
    status: 'submitted',
    reject_reason_code: null,
    reject_reason_text: null,
    created_at: minutesAgo(42),
    updated_at: minutesAgo(42),
  },
  {
    id: 'case-sy-1054',
    external_id: 'SY-1054',
    citizen_id: 'citizen-006',
    block_id: 'blk-koramangala',
    shelter_id: 'shelter-eastside',
    category: 'water',
    severity: 'today',
    description: 'Water station empty near park entrance. Bowls are dry.',
    location_text: 'Koramangala Park, Gate 2',
    status: 'under_review',
    reject_reason_code: null,
    reject_reason_text: null,
    created_at: minutesAgo(100),
    updated_at: minutesAgo(60),
  },
  {
    id: 'case-sy-8830',
    external_id: 'SY-8830',
    citizen_id: 'citizen-005',
    block_id: 'blk-indiranagar',
    shelter_id: 'shelter-indiranagar',
    category: 'feeding',
    severity: 'soon',
    description: 'Small pack near metro exit needs evening feeding route.',
    location_text: 'Indiranagar Metro Exit B',
    status: 'assigned',
    reject_reason_code: null,
    reject_reason_text: null,
    created_at: minutesAgo(210),
    updated_at: minutesAgo(55),
  },
  {
    id: 'case-sy-4922',
    external_id: 'SY-4922',
    citizen_id: 'citizen-003',
    block_id: 'blk-jayanagar',
    shelter_id: 'shelter-cubbon',
    category: 'sick',
    severity: 'urgent',
    description: 'Cat appears lethargic and has discharge around eyes.',
    location_text: 'Jayanagar 4th Block bus stop',
    status: 'in_progress',
    reject_reason_code: null,
    reject_reason_text: null,
    created_at: minutesAgo(320),
    updated_at: minutesAgo(25),
  },
  {
    id: 'case-sy-6118',
    external_id: 'SY-6118',
    citizen_id: 'citizen-004',
    block_id: 'blk-whitefield',
    shelter_id: 'shelter-whitefield',
    category: 'abandoned',
    severity: 'today',
    description: 'Two puppies left near apartment gate. Security has placed water nearby.',
    location_text: 'Whitefield Palm Meadows gate',
    status: 'task_created',
    reject_reason_code: null,
    reject_reason_text: null,
    created_at: minutesAgo(480),
    updated_at: minutesAgo(400),
  },
  {
    id: 'case-sy-7288',
    external_id: 'SY-7288',
    citizen_id: 'citizen-002',
    block_id: 'blk-koramangala',
    shelter_id: 'shelter-eastside',
    category: 'injured',
    severity: 'urgent',
    description: 'Limping dog was moved to a shaded area and checked by partner shelter.',
    location_text: 'Koramangala 5th Block signal',
    status: 'resolved',
    reject_reason_code: null,
    reject_reason_text: null,
    created_at: minutesAgo(1_440),
    updated_at: minutesAgo(1_070),
  },
  {
    id: 'case-sy-3021',
    external_id: 'SY-3021',
    citizen_id: 'citizen-001',
    block_id: 'blk-indiranagar',
    shelter_id: null,
    category: 'other',
    severity: 'soon',
    description: 'Same animal and location as SY-8830.',
    location_text: 'Indiranagar Metro Exit B',
    status: 'rejected',
    reject_reason_code: 'duplicate_case',
    reject_reason_text: 'Duplicate of SY-8830. Citizen notified.',
    created_at: minutesAgo(1_800),
    updated_at: minutesAgo(1_760),
  },
];

export const demoTasks: TaskRow[] = [
  {
    id: 'task-rescue-7421',
    case_id: 'case-sy-7421',
    template_id: 'tpl-rescue',
    block_id: 'blk-indiranagar',
    shelter_id: null,
    external_ref: null,
    status: 'queued',
    priority: 'critical',
    assigned_to_type: null,
    assigned_to_id: null,
    due_at: minutesFromNow(18),
    created_at: minutesAgo(35),
    updated_at: minutesAgo(35),
  },
  {
    id: 'task-water-1054',
    case_id: 'case-sy-1054',
    template_id: 'tpl-water',
    block_id: 'blk-koramangala',
    shelter_id: 'shelter-eastside',
    external_ref: null,
    status: 'assigned',
    priority: 'high',
    assigned_to_type: 'shelter',
    assigned_to_id: 'shelter-eastside',
    due_at: minutesFromNow(95),
    created_at: minutesAgo(90),
    updated_at: minutesAgo(40),
  },
  {
    id: 'task-feed-8830',
    case_id: 'case-sy-8830',
    template_id: 'tpl-feed',
    block_id: 'blk-indiranagar',
    shelter_id: 'shelter-indiranagar',
    external_ref: 'mission:demo-device-biscuit-feeder:feed-8830',
    status: 'proof_pending',
    priority: 'medium',
    assigned_to_type: 'citizen',
    assigned_to_id: 'demo-device-biscuit-feeder',
    due_at: minutesFromNow(120),
    created_at: minutesAgo(180),
    updated_at: minutesAgo(20),
  },
  {
    id: 'task-medical-4922',
    case_id: 'case-sy-4922',
    template_id: 'tpl-medical',
    block_id: 'blk-jayanagar',
    shelter_id: 'shelter-cubbon',
    external_ref: null,
    status: 'in_progress',
    priority: 'critical',
    assigned_to_type: 'shelter',
    assigned_to_id: 'shelter-cubbon',
    due_at: minutesFromNow(35),
    created_at: minutesAgo(250),
    updated_at: minutesAgo(15),
  },
  {
    id: 'task-transfer-6118',
    case_id: 'case-sy-6118',
    template_id: 'tpl-transfer',
    block_id: 'blk-whitefield',
    shelter_id: 'shelter-whitefield',
    external_ref: null,
    status: 'blocked',
    priority: 'high',
    assigned_to_type: 'shelter',
    assigned_to_id: 'shelter-whitefield',
    due_at: minutesAgo(45),
    created_at: minutesAgo(420),
    updated_at: minutesAgo(70),
  },
  {
    id: 'task-medical-7288',
    case_id: 'case-sy-7288',
    template_id: 'tpl-medical',
    block_id: 'blk-koramangala',
    shelter_id: 'shelter-eastside',
    external_ref: null,
    status: 'completed',
    priority: 'critical',
    assigned_to_type: 'shelter',
    assigned_to_id: 'shelter-eastside',
    due_at: minutesAgo(1_120),
    created_at: minutesAgo(1_390),
    updated_at: minutesAgo(1_070),
  },
];

export const demoProofs: ProofRow[] = [
  {
    id: 'proof-feed-8830',
    task_id: 'task-feed-8830',
    photo_uri: 'https://images.unsplash.com/photo-1548199973-03cce0bbc87b?auto=format&fit=crop&w=1200&q=60',
    note: 'Fed at 6:10pm. Pack stayed calm and finished food.',
    captured_at: minutesAgo(28),
    submitted_at: minutesAgo(25),
    verification_status: 'pending',
    created_at: minutesAgo(25),
  },
  {
    id: 'proof-water-1054',
    task_id: 'task-water-1054',
    photo_uri: 'https://images.unsplash.com/photo-1568572933382-74d440642117?auto=format&fit=crop&w=1200&q=60',
    note: 'Water bowls refilled and cleaned. Need replacement bowl next visit.',
    captured_at: minutesAgo(48),
    submitted_at: minutesAgo(44),
    verification_status: 'needs_review',
    created_at: minutesAgo(44),
  },
  {
    id: 'proof-medical-7288',
    task_id: 'task-medical-7288',
    photo_uri: 'https://images.unsplash.com/photo-1537151625747-768eb6cf92b2?auto=format&fit=crop&w=1200&q=60',
    note: 'Partner shelter confirmed wound cleaned and follow-up booked.',
    captured_at: minutesAgo(1_090),
    submitted_at: minutesAgo(1_085),
    verification_status: 'verified',
    created_at: minutesAgo(1_085),
  },
  {
    id: 'proof-rejected-blur',
    task_id: 'task-transfer-6118',
    photo_uri: 'local://blurred-proof-demo.jpg',
    note: 'Photo too blurry to verify transfer.',
    captured_at: minutesAgo(80),
    submitted_at: minutesAgo(78),
    verification_status: 'rejected',
    created_at: minutesAgo(78),
  },
];
