/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./app/**/*.{ts,tsx}', './components/**/*.{ts,tsx}'],
  presets: [require('nativewind/preset')],
  theme: {
    extend: {
      colors: {
        jungle: '#2DC653',
        'jungle-deep': '#1B8A36',
        'jungle-soft': '#DFF6E3',
        'jungle-ink': '#0F4C20',
        coral: '#FF5A4A',
        'coral-deep': '#C92F22',
        'coral-soft': '#FFE2DC',
        'coral-ink': '#6B1A12',
        gold: '#FFC83D',
        'gold-deep': '#C98E00',
        'gold-soft': '#FFF1C8',
        'gold-ink': '#5C3F00',
        sky: '#1CB0F6',
        'sky-deep': '#0E83B9',
        'sky-soft': '#D6F2FF',
        plum: '#A560E8',
        'plum-deep': '#7733C2',
        'plum-soft': '#F0E0FF',
        paper: '#FFFCEF',
        'paper-2': '#F7F0DA',
        'paper-3': '#ECE2C5',
        surface: '#FFFFFF',
        ink: '#1A1B1F',
        'ink-2': '#424551',
        muted: '#7C7E8A',
        hairline: '#E8E1CD',
        'hairline-2': '#D8CFB4',
      },
      fontFamily: {
        display: ['Fredoka'],
        body: ['Nunito'],
        mono: ['JetBrainsMono'],
      },
      borderRadius: {
        'sm': '12px',
        'md': '18px',
        'lg': '24px',
        'xl': '32px',
        'pill': '9999px',
      },
    },
  },
  plugins: [],
};
